version: '3.9'
services:
  nginx:
    image: nginx
    restart: unless-stopped
    env_file:
      - ./.srv/.env
    ports:
      - 8088:80
    volumes:
      - ./.srv/nginx:/etc/nginx/conf.d:rw

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./.srv/database:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: x1team
      MYSQL_USER: x1team
      MYSQL_PASSWORD: x1team
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']


  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:80
      - 443:443
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: x1team
      WORDPRESS_DB_PASSWORD: x1team
      WORDPRESS_DB_NAME: x1team
      WORDPRESS_DEBUG: 1
    volumes:
      - ./.srv/wordpress/:/var/www/html
      - ./theme/:/var/www/html/wp-content/themes/me
      - ./plugin-one/:/var/www/html/wp-content/plugins/pkg
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./logs:/var/www/html/wp-content/logs
      - ./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: x1team
      MYSQL_PASSWORD: x1team
      PMA_HOST: mysql